Preparation for AW-1
fetchai/docs-archived pull request #113
Opened 2020-10-19 15:12 UTC by DavidMinarsch

This PR:
- restructures navigation in docs
- adds content on incentivised test-nets in general and aw-1 in particular
- adds minimal docs on ledger v2

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/css/my-styles.css
>      border: solid 1px lightgrey;
Temporary..needs proper styling

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/i_nets/index.md
> +Incentivized testnets. ...General intro to incentivized testnets;
Placeholder text. @CobrasCobras please add

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/i_nets/quickstart-aw1.md
> +## Intro
WIP, subject to change

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/index.md
> +    <h4>Another box goes here to draw attention to latest running testnet and prizes on offer, colour different!</h4>
@CobrasCobras headline needed

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/ledger/index.md
> -# Fetch.ai ledger
still present, moved to `ledger_v1` dir

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/ledger/index.md
> +<div class="grid-item item_whole_row no-padding">
Main index site for ledger

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/ledger_v1/index.md
> +<div class="admonition note">
Copy past from old `ledger` dir, added note on top

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/ledger_v2/index.md
> +# Getting Ready for Mainnet V2
@CobrasCobras text you provided me with

2020-10-19 15:17 UTC, DavidMinarsch commented on docs/playground.md
> -## The most basic introduction
not needed anymore

2020-10-19 15:17 UTC, DavidMinarsch commented on theme/custom_theme/base.html
> +<!--                             <li><a href="https://testnet-wallet.fetch.ai/">Testnet wallet</a></li> -->
very problematic and confusing, removed

2020-10-21 14:01 UTC, CobrasCobras requested changes
Some initial comments:

- Some of the links under "Key links and information" on the "Getting Ready for Mainnet V2" page are not links, they are just plain text
- On home, change "Another box goes here to draw attention to latest running testnet and prizes on offer, colour different!" to read:

> ** Fetch.ai Incentivized testnets are running __now__**
> You can learn more about this journey at [link to the Introduction diagram]. The current running testnet is Agent themed, and you can get part of a substantial reward pool over the coming weeks. Each themed testnet divides its focus up into different pieces, so there's something for everyone. Get started now [link to agent world]!

@steevi may wish to review the "Getting Ready for Mainnet V2" piece given the links, end-points, etc. And we do need to point at the right inventivised testnet and not just agent land. 

Also, in "Getting Ready for Mainnet V2: there is a subsection that is labeled:
> Converting Agents to be ready for Mainnet v2
> Ask David M to fill this in and link to correct place in the AEA docs.

Replace "Incentivized testnets. ...General intro to incentivized testnets;" with:
> ## The Journey to mainnet version 2
> Fetch.ai is running three themed, incentivized testnets to take us to mainnet version 2. Each testnet will run for approximately 6 weeks, and will be arranged in groups of incentives. The below diagram outlines how this will work. When each incentivized testnet is complete, it will be reset and the new one created. This will reset state, and testing and work will focus on the new functionality added. With each step along the way, we get closer and closer to a fully featured Fetch V2 mainnet.
> Throughout this process, Fetch.ai is running a __stable testnet__ called Agentland. Agentland will not have its state reset, and is perfect for application and agent development and deployment.
> When the funky incentivized testnet is complete, mainnet v2 will be launched.

2020-10-21 15:45 UTC, steevi commented on docs/ledger_v2/index.md
> +**Token Faucet:** https://faucet-agent-land.fetch.ai/claim
This is plain text, as it will not reply to GET requests. It will reply only on POST with parameters `Address=<address>`

2020-10-22 09:23 UTC, merged