Add/learn decentral
fetchai/docs-archived pull request #221
Opened 2022-04-11 16:46 UTC by 5A11

This PR adds `decentralisation` page.

2022-04-12 08:13 UTC, 5A11 commented on docs/decentralisation.md
> +Another great example is when you fly internationally from one place to another. There are numerous participants working together and communicating equitably together to make that a seamless experien
equitably is a difficult word. Replace.

2022-04-12 08:21 UTC, 5A11 commented on docs/decentralisation.md
> +* Amazon: Buyers and sellers interact commercially through Amazon.
```suggestion
* Amazon: Buyers and sellers interact commercially through Amazon.
* Client-Server model: The conventional client-server application model is an example of a centralized architecture where clients interact with one another only through the server.
```

2022-04-12 08:24 UTC, 5A11 commented on docs/decentralisation.md
> +Decentralised systems are useful because they solve the issue of trust. Users don't have to trust a central authority, which itself has the motivation to behave in its own interests and agenda but ra
The last sentence is not quite correct.

2022-04-12 08:25 UTC, 5A11 commented on docs/decentralisation.md
> +Decentralised systems are useful because they solve the issue of trust. Users don't have to trust a central authority, which itself has the motivation to behave in its own interests and agenda but ra
Generally, this paragraph isn't ideal. Why decentralised system? we essentially want to point to the positive points below and say when you want these characteristics, decentralisation is your choice.

2022-04-12 08:31 UTC, 5A11 commented on docs/decentralisation.md
> +Decentralised systems are useful because they solve the issue of trust. Users don't have to trust a central authority, which itself has the motivation to behave in its own interests and agenda but ra
The point about trust can be made one of the positive points below.

**Trust minimisation**: The fact that in decentralised systems, participants do not have to go through central authorities to interact with others and achieve their goals means there is no need to trust central entities to handle your needs. Any guarantees needed by the system has to be provided by the system itself and they way it is designed and (due to Transparency) this is typically well known.

Put this after `Transparency`.

2022-04-12 11:43 UTC, 5A11 commented on docs/decentralisation.md
> +* **Democratic** Decentralized systems require participation in order to successfully function, and therefore they are intrinsically democratic systems.
intrinsically is too difficult. Replace (e.g. `by nature`, `naturally`, ...).

2022-04-12 11:46 UTC, 5A11 commented on docs/decentralisation.md
> +In order for the participants of a decentralized system to contribute to its liveliness, they must be aware of how the system works, how it is managed, and so on. Therefore, decentralized systems ten
```suggestion
In order for the participants of a decentralized system to contribute to its liveliness, they must be made aware of how the system works, how it is managed, and so on. Decentralized systems therefore tend to be quite transparent.
```

2022-04-12 11:49 UTC, 5A11 commented on docs/decentralisation.md
> +
Main drawbacks are speed/efficiency and simplicity. Decentralised version of a centralisazed system is almost always less efficient at achieving the same result (exactly because there is not a single decision maker, rather a collection of decision makers). Also it takes more engineering to create a decentralised architecture for a system over a centralised one. The patrol example is good in this regard.

2022-04-12 11:50 UTC, 5A11 commented on docs/decentralisation.md
> +* **Speed**: Decentralized systems are often slower than centralized systems, as there is no single authority with an interest in making the system as fast as possible and individual participants may
Shouldn't say `there is no single authority with an interest in making the system as fast as possible`. The system is owned by the owners of the participants and it is in their interest the system runs as fast as possible.

2022-04-12 11:54 UTC, 5A11 commented on docs/decentralisation.md
> +* **Speed**: Decentralized systems are often slower than centralized systems, as there is no single authority with an interest in making the system as fast as possible and individual participants may
The system is slower because there is more than one decision maker and arriving at a consensus in a group takes more time than a single entity making decisions. Also the other characteristics (e.g. openness) makes the system less efficient (should allow anyone to come in/leave so the system must be designed to cope with this).

2022-04-12 12:00 UTC, 5A11 commented on docs/decentralisation.md
> +* **Control**: As control is shared by participants, controlling and managing the system is more complicated and slower.
```suggestion
* **Control**: Because a decentrralized system is often run collectively by its participants, controlling how the system is managed and the development direction it takes is difficult.
```

2022-04-12 12:00 UTC, 5A11 commented on docs/decentralisation.md
> +* **Privacy**: The requirement for participation inevitably results in a loss of privacy as participants need to actively engage with other participants in order to manage and make decisions about th
Shouldn't say this.

2022-04-12 12:00 UTC, 5A11 commented on docs/decentralisation.md
> +* **Anonymity**: There are times and situations where participants may actually want to be anonymous, and this is something that decentralized systems do not really allow.
Shouldn't say this.

2022-04-12 12:07 UTC, 5A11 commented on docs/decentralisation.md
> +* **Anonymity**: There are times and situations where participants may actually want to be anonymous, and this is something that decentralized systems do not really allow.
Instead add:

* **Simplicity**: it takes more engineering to enable openness and allow a decentralized system to achieve the same result a centralized one achieves with a single authority, via a group of (maybe heterogeneous) nodes. Moreover, providing the same guarantees that a centralized system ensures via the central enforcer but via proper mechanism design makes for a far more complicated system design.

2022-04-12 12:07 UTC, 5A11 commented on docs/decentralisation.md
> +* **Anonymity**: There are times and situations where participants may actually want to be anonymous, and this is something that decentralized systems do not really allow.
Edit the above.

2022-04-12 13:45 UTC, eallen288 commented on docs/decentralisation.md
> +Another great example is when you fly internationally from one place to another. There are numerous participants working together and communicating equitably together to make that a seamless experien
Have replaced it.

2022-04-12 13:46 UTC, eallen288 commented on docs/decentralisation.md
> +Decentralised systems are useful because they solve the issue of trust. Users don't have to trust a central authority, which itself has the motivation to behave in its own interests and agenda but ra
Have made these changes:

- Rephrased Why decentralized systems.
-Added Trust minimisation point in.

2022-04-12 13:50 UTC, eallen288 commented on docs/decentralisation.md
> +* **Democratic** Decentralized systems require participation in order to successfully function, and therefore they are intrinsically democratic systems.
```suggestion
* **Democratic** Decentralized systems require participation in order to successfully function, and therefore they are naturally democratic systems.
```

2022-04-12 13:51 UTC, eallen288 commented on docs/decentralisation.md
> +
Have made this change to the text.

2022-04-12 13:51 UTC, eallen288 commented on docs/decentralisation.md
> +* **Anonymity**: There are times and situations where participants may actually want to be anonymous, and this is something that decentralized systems do not really allow.
Made this change as requested.

2022-04-27 03:27 UTC, 5A11 commented on docs/decentralisation.md
> +A decentralized system is an interconnected system where no single central entity (individual, organization, or group) is the sole authority. In a decentralized system, control and decision-making is
```suggestion
A decentralized system is an interconnected system where no single entity (individual, organization, or group) is the sole authority. In a decentralized system, control and decision-making is done by those participating in the system where they have (more or less) equal standing in terms of influence. This is in contrast to a centralized system where a central authority is above all others in terms of rights and privileges.
```

2022-04-27 03:41 UTC, 5A11 commented on docs/decentralisation.md
> +A good example of a decentralized system is the world’s telephone system; there is no central authority that runs it but numerous participants coordinate together to make it work.
```suggestion
A good example of a decentralized system is an ant colony where control is distributed among the colony's members. Without any form of central control, an ant colony achieves its goals, performs the required tasks, and responds to changing conditions in the colony's environment via the collective contribution of individual ants.
```

2022-04-27 03:41 UTC, 5A11 commented on docs/decentralisation.md
> +Another great example is when you fly internationally from one place to another. There are numerous participants working together and communicating efficiently to make that a seamless experience.
```suggestion
```

2022-04-27 03:43 UTC, 5A11 commented on docs/decentralisation.md
> +Another great example is when you fly internationally from one place to another. There are numerous participants working together and communicating efficiently to make that a seamless experience.
```suggestion
Another great example is when you fly internationally from one place to another. There are numerous participants working together and communicating efficiently to make that a seamless experience without there being a central unit that plans it all.
```

2022-04-27 03:46 UTC, 5A11 commented on docs/decentralisation.md
> +In a centralized system, there is a central authority that manages the system and makes decisions about how it is run.
```suggestion
In a centralized system, there is a central authority that manages the system, makes decisions about how it is run and exercises control over the other components of the system.
```

2022-04-27 03:48 UTC, 5A11 commented on docs/decentralisation.md
> +There are 4 key positive characteristics of decentralized systems:
```suggestion
There are 5 key positive characteristics of decentralized systems:
```

2022-04-27 03:52 UTC, 5A11 commented on docs/decentralisation.md
> +Because decentralized systems are managed and run by their participants (Democratic) and anyone can in principle join the system or leave (Open), these systems tend to be public and their inner worki
```suggestion
Because decentralized systems need to be managed and run by their participants (Democratic) and anyone can in principle join the system or leave (Open), these systems are often public and their inner workings are not kept confidential.
```

2022-04-27 03:53 UTC, 5A11 commented on docs/decentralisation.md
> +* **Trust minimisation** The fact that in decentralised systems, participants do not have to go through central authorities to interact with others and achieve their goals means there is no need to t
```suggestion
* **Trust minimisation** The fact that in decentralised systems, participants do not have to go through central authorities to interact with others and achieve their goals means there is no need to trust central entities to handle your needs. Any guarantees needed by the system has to be provided by the system itself and the way it is designed, and (due to Transparency) this is typically well known.
```

2022-04-27 03:54 UTC, 5A11 commented on docs/decentralisation.md
> +The main limitations of decentralized systems are speed/efficiency and simplicity. A decentralized version of a centralized system is almost always less efficient at achieving the same result (exactl
This needs to be written more diplomatically.

2022-04-27 03:57 UTC, 5A11 commented on docs/decentralisation.md
> +Compared with a centralized system, decentralized architechture is more complex and therefore it takes more engineering to  create the decentralised architecture for a system compared to a centralise
The above two paragraphs need to be rewritten for style and hasve to be made more diplomatic.

2022-04-27 03:57 UTC, 5A11 commented on docs/decentralisation.md
> +For example a company payroll system would not make sense to decentralize as you want central authority over it and need a system that is simple to manage and quick to operate.
No need for an example.

2022-04-27 03:58 UTC, 5A11 commented on docs/decentralisation.md
> +* **Speed**: Decentralized systems are often slower than centralized systems, because there is more than one decision maker, decisions have to be made by consensus in the group and arriving at that c
```suggestion
* **Speed**: Decentralized systems are often slower than centralized systems. Because there is more than one decision maker, decisions have to be made by consensus in the group and arriving at that consensus takes more time than a single entity making the decision.  
```

2022-04-27 04:01 UTC, 5A11 commented on docs/decentralisation.md
> +* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the development direction it takes is difficult.
```suggestion
* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
```

2022-04-27 04:03 UTC, 5A11 commented on docs/decentralisation.md
> +* **Simplicity**: It is more complex to engineer a decentralized system to enable openness and allow a decentralized system to achieve the same result that a centralized one achieves with a single au
```suggestion
* **Simplicity**: It is often more complex to engineer a decentralized architecture for a system and enable openness than to achieve the same goals via a central enforcer. 
```

2022-04-27 04:06 UTC, 5A11 commented on docs/decentralisation.md
> +
Needs a closing paragraph/conclusion.

2022-05-25 09:36 UTC, VijaySharma815 requested changes

2022-05-25 09:36 UTC, VijaySharma815 commented on docs/decentralisation.md
> +Decentralised systems are useful because they are open and democratic, more transparent, and they are run solely in the interests of their participants by their participants.
_They are run solely in the interest of their participants by their participants can be written in a more simplified form,_ it's a bit confusing at the moment.

2022-05-25 10:12 UTC, VijaySharma815 requested changes, later dismissed

2022-05-25 10:12 UTC, VijaySharma815 commented on docs/decentralisation.md
> +* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
**Suggestion:**  Limitations>control> 

We can add:
" No one owns the data but simultaneously everyone owns the data"

2022-05-30 10:09 UTC, 5A11 commented on docs/decentralisation.md
> +Decentralised systems are useful because they are open and democratic, more transparent, and they are run solely in the interests of their participants by their participants.
suggestion?

2022-05-30 10:09 UTC, 5A11 commented on docs/decentralisation.md
> +Decentralised systems are useful because they are open and democratic, more transparent, and they are run solely in the interests of their participants by their participants.
suggestion?

2022-05-30 10:12 UTC, 5A11 commented on docs/decentralisation.md
> +* **Efficiency**: Decision making about the system requires participation, which makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because
```suggestion
* **Efficiency**: In decentralized systems, decision making about the system requires participation. This makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because the system is open, so participants can leave/join as they wish, then the system has to be designed to cope with an often changing number of participants. All this added complexity inevitably affects the efficiency of the system's operation.
```
```suggestion
* **Efficiency**: Decision making about the system requires participation, which makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because the system is open, so participants can leave/join as they wish, then the system has to be designed to cope with an often changing number of participants. All this added complexity inevitably affects the efficiency of the operation of the system.
```

2022-05-30 10:12 UTC, 5A11 commented on docs/decentralisation.md
> +* **Efficiency**: Decision making about the system requires participation, which makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because
```suggestion
* **Efficiency**: In decentralized systems, decision making about the system requires participation. This makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because the system is open, so participants can leave/join as they wish, then the system has to be designed to cope with an often changing number of participants. All this added complexity inevitably affects the efficiency of the system's operation.
```
```suggestion
* **Efficiency**: Decision making about the system requires participation, which makes it far slower to make changes to the system as it takes time for participants to agree to changes. Also because the system is open, so participants can leave/join as they wish, then the system has to be designed to cope with an often changing number of participants. All this added complexity inevitably affects the efficiency of the operation of the system.
```

2022-05-30 10:14 UTC, 5A11 commented on docs/decentralisation.md
> +* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
Though a valid point, it doesn't really fit here. The point here is about having ownership and thus control over the whole system and how it is managed, run, developed, etc.

2022-05-30 10:15 UTC, 5A11 commented on docs/decentralisation.md
> +* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
See if you can integrate this point elsewhere.

2022-06-06 07:38 UTC, VijaySharma815 commented on docs/decentralisation.md
> +Decentralised systems are useful because they are open and democratic, more transparent, and they are run solely in the interests of their participants by their participants.
Suggestion is only that we can write in more simplified form/manner.

2022-08-23 11:08 UTC, 5A11 commented on docs/decentralisation.md
> +A decentralized system is an interconnected system where no single entity (individual, organization, or group) is the sole authority. In a decentralized system, control and decision-making is done by
More personal
```suggestion
A decentralized system is an interconnected system if no single entity (individual, organization, or group) is the sole authority. In a decentralized system, control and decision-making is in the hands of those participating in the system and they have (more or less) equal standing in terms of influence. This is in contrast to a centralized system where a single authority is above all others in terms of rights and privileges.
```

2022-08-23 11:16 UTC, 5A11 commented on docs/decentralisation.md
> +In a decentralized system, a key feature is that the participants contribute together to the control and decision-making of the system, with each of them taking an active equal role in managing the s
```suggestion
* **Equality of participants**: the participants contribute together to decision-making in the system, with each of them taking an active equal role in managing the system. 
```

2022-08-23 11:19 UTC, 5A11 commented on docs/decentralisation.md
> +It is not that decentralized systems lack authority to make changes to the management of the network, but the authority to do that is distributed among the participants. The system is run by the part
```suggestion
* **Lack of central authorities**: It is not that decentralized systems lack the authority to make changes to the management of the network, rather this authority is distributed among the participants. The system is run by the participants for the benefit of the participants.
```

2022-08-23 11:20 UTC, 5A11 commented on docs/decentralisation.md
> +What determines whether a system is decentralized or not is whether or not there is a central authority. What determines whether a system is distributed is whether the processing is done in one or mu
```suggestion
What determines whether a system is decentralized or not is whether or not there are central authorities. What determines whether a system is distributed is whether the processing is done in one or multiple physical locations. 
```

2022-08-23 11:23 UTC, 5A11 commented on docs/decentralisation.md
> +These are some of the key properties of decentralized systems:
```suggestion
These are some of the key benefits of decentralized systems:
```

2022-08-23 11:24 UTC, 5A11 commented on docs/decentralisation.md
> +* **Democratic** Decentralized systems require participation in order to successfully function, and therefore they are naturally democratic systems.
```suggestion
* **Democratic**: Decentralized systems require participation in order to successfully function, and therefore they are naturally democratic systems.
```

2022-08-23 11:24 UTC, 5A11 commented on docs/decentralisation.md
> +Participants can freely join or leave as they wish,. The system is open to new participants and does not stop existing ones leaving.
```suggestion
* **Open**: Participants can freely join or leave as they wish,. The system is open to new participants and does not stop existing ones leaving.
```

2022-08-23 11:24 UTC, 5A11 commented on docs/decentralisation.md
> +Because decentralized systems need to be  managed and run by their participants (Democratic) and anyone can in principle join the system or leave (Open), these systems are often public and their inne
```suggestion
* **Public**: Because decentralized systems need to be  managed and run by their participants (Democratic) and anyone can in principle join the system or leave (Open), these systems are often public and their inner workings are not kept confidential.
```

2022-08-23 11:25 UTC, 5A11 commented on docs/decentralisation.md
> +In order for the participants of a decentralized system to contribute to its liveliness, they must be made aware of how the system works, how it is managed, and so on. Decentralized systems therefore
```suggestion
* **Transparent**: In order for the participants of a decentralized system to contribute to its liveliness, they must be made aware of how the system works, how it is managed, and so on. Decentralized systems therefore tend to be quite transparent. 
```

2022-08-23 11:26 UTC, 5A11 commented on docs/decentralisation.md
> +* **Trust minimisation** The fact that in decentralised systems, participants do not have to go through central authorities to interact with others and achieve their goals means there is no need to t
```suggestion
* **Trust minimisation**: The fact that in decentralised systems, participants do not have to go through central authorities to interact with others and achieve their goals means there is no need to trust central entities to handle your needs. Any guarantees needed by the system has to be provided by the system itself and the way it is designed, and (due to Transparency) this is typically well known.
```

2022-08-23 11:28 UTC, 5A11 commented on docs/decentralisation.md
> +* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
```suggestion
* **Control**: Because a decentralized system is often run collectively by its participants, controlling how the system is managed and the direction of its development is difficult.
```

2022-08-23 11:30 UTC, 5A11 commented on docs/decentralisation.md
> +* **Simplicity**: For any system, it is often more complex to engineer a decentralized architecture and enable openness than to design a centralized one to achieves the same system goals via a centra
```suggestion
* **Simplicity**: For any system, it is often more complex to engineer a decentralized version which enables openness than a centralized one that achieves the same goals via central enforcers. 
```

2022-08-23 11:32 UTC, 5A11 commented on docs/decentralisation.md
> +It is clear that a system with more than one decision maker is going to be more complex to engineer than one where all the decisions are made by a single authority. This is because there needs to be
```suggestion
```

2022-08-23 11:33 UTC, 5A11 commented on docs/decentralisation.md
> +It is clear that a system with more than one decision maker is going to be more complex to engineer than one where all the decisions are made by a single authority. This is because there needs to be
This is repeated below. Also it breaks the pattern of the section above.

2022-08-23 11:35 UTC, 5A11 reviewed
Most of the comments are made to make the text more personal and less academic.

2022-09-04 07:28 UTC, VijaySharma815 commented on docs/decentralisation.md
> +* **Public**: Because decentralized systems need to be  managed and run by their participants (Democratic) and anyone can in principle join the system or leave (Open), these systems are __often__ pub
Because decentralized systems need to be  managed and run by their participants -> Because decentralized systems need to be managed and run by their participants

2022-09-04 07:28 UTC, VijaySharma815 commented on docs/decentralisation.md
> +* **Open**: Participants can freely join or leave as they wish,. The system is open to new participants and does not stop existing ones leaving.
Participants can freely join or leave as they wish,. 

The punctuation is incorrect.

2022-09-22 08:55 UTC, jrriehl commented on docs/decentralisation.md
> +* **Equality of participants**: all participants contribute towards the system's decision-making and control, and each of them takes an active equal role in managing the system.
Saying each participant takes an equal role may be a bit too strong. In proof-of-stake consensus for example, voting power often depends on how much the participant has staked.

2022-09-22 08:57 UTC, jrriehl commented on docs/decentralisation.md
> +Decentralised systems are useful because they are open and democratic, more transparent, and they are run solely in the interests of their participants by their participants.
We should probably be consistent with decentralized vs decentralised.

2022-09-22 09:00 UTC, jrriehl reviewed
Just a couple of minor suggestions, otherwise it looks good!

2022-11-11 10:05 UTC, FelixNicolaeBucsa approved these changes

2022-11-11 10:06 UTC, merged