docs: add Ledger Explorer (placeholder) (ECO-1270)
fetchai/docs-archived pull request #223
Opened 2022-04-14 14:56 UTC by bryanchriswhite

### Changes
- adds ledger-explorer to navigation
- adds ledger-explorer docs placeholder* directory 
- adds initial user guide

*I'm assuming we want to add the ledger-explorer repo as a submodule and move the docs into it.

2022-04-19 14:22 UTC, 5A11 requested changes
For consistency, add this as a submodule to this repo, similar to the rest of the submodules (aea, cosmpy etc).

You reference this as for the ledger explorer but the content is for the wallet :) 
Please rectify (PR name, folder names, mkdocs.yaml, etc).

Let's break the content up into the following pages:
- Browser-Extension Wallet
  - Getting started: Intro, How to get, Requirements, Version, How to contribute (repo)
  - Account management: Create a new account, Import an existing account, Mnemonic, Hardware wallet, Switch accounts, Remove account, (and maybe "Migrating from ETH"? or maybe this should go somewhere else?)
  - Send tokens: Native transfer, IBC transfer
  - Deposit: How to top up your account
  - Stake: Intro (point to staking under explorer), Claim rewards

2022-04-19 14:24 UTC, 5A11 commented on ledger-explorer/docs/index.md
> +## First-time use
Add "How to get" with instructions on how/where to get this.
Also add requirements (e.g. state the fact it is a chrome extension and so needs chrome).

2022-04-19 14:24 UTC, 5A11 commented on ledger-explorer/docs/index.md
> +- [Create a new account](#creating-a-new-account)
Needs a line break before this to make it a proper list.

2022-04-19 19:24 UTC, bryanchriswhite commented
> You reference this as for the ledger explorer but the content is for the wallet :)

🤦

2022-04-21 15:18 UTC, 5A11 commented on .gitmodules
> +[submodule "keplr-extension"]
I don't like this name :/
Is there any way to just have `browser-extension wallet` or does it have to mirror the repo name?

2022-06-02 15:05 UTC, bryanchriswhite commented on .gitmodules
> +[submodule "keplr-extension"]
I looks like we can change submodule name and path independently of the URL. Path is the one that would affect the the directory name on the filesystem. I think changing the submodule name would only affect git submodule commands.

It seems like this might not be necessary though now that we've decided we're going to rename the wallet repo, right?

2022-06-22 08:29 UTC, bryanchriswhite commented on docs/basics/wallet/getting_started.md
> +If you have an account on the Fetch network, for example having had one already on the Fetch wallet and want to access it again, have an account on another wallet (e.g. Cosmostation, Keplr, ...) and
:100:

2022-06-22 08:35 UTC, bryanchriswhite reviewed
Thanks @5A11, you're improvements are wonderful! :ok_hand:

2022-06-22 08:37 UTC, 5A11 approved these changes
lgtm

2022-06-22 09:14 UTC, merged