add styling to homepage, still needs responsiveness
fetchai/docs-archived pull request #232
Opened 2022-05-17 09:56 UTC by StephenBrownFetch

2022-05-18 07:19 UTC, 5A11 commented
Couple of points:
* I really am not a fan of the pictures on the home page. I think we need to get them properly designed otherwise to me text-only is better (especially because the content of the home page has to update soon anyway).
* The link hover shade is nicely implemented. But it sometimes messes up the link text's formatting and gets the text into a new line. I think its size/margin/padding/etc needs retouching.
* The header's colour is too blue, resembling a clickable link.

2022-05-18 08:52 UTC, GataKamsky commented
My comments:

1. I like the overall idea of inserting more visual elements to break the monotony of blob of text. Though, my personal preference is going in the direction of [Cosmos Documentation homepage](https://docs.cosmos.network/). It has a more clean and professional feel to it. Can we get a similar professional look as the Cosmos page? These card colors are attracting too much attention. I would suggest trying to go with white cards with more professional looking visual assets from our graphics designer.
2. @5A11 this page content needs changing as it largely talks about AEA and SOEF. We have moved SOEF content to archive and homepage brings it front and center. 
3. I also like the link hover implementation. And notice the point @5A11 makes. If there is an elegant way to fix it then we should. But I would also be ok if we go out with this version and refine it later.
4. For some reason 'Apply for $150M Developer Fund' has come back into the Nav list. This is meant to stay in the banner at the top as in the live docs version.
5. I noticed one strange behavior, when using on-page nav (on the right side of the content), we are losing the banner on the page both in the live and test versions.

2022-05-18 09:04 UTC, 5A11 commented
> My comments:
> 
> 1. I like the overall idea of inserting more visual elements to break the monotony of blob of text. Though, my personal preference is going in the direction of [Cosmos Documentation homepage](https://docs.cosmos.network/). It has a more clean and professional feel to it. Can we get a similar professional look as the Cosmos page? These card colors are attracting too much attention. I would suggest trying to go with white cards with more professional looking visual assets from our graphics designer.
> 2. @5A11 this page content needs changing as it largely talks about AEA and SOEF. We have moved SOEF content to archive and homepage brings it front and center.
> 3. I also like the link hover implementation. And notice the point @5A11 makes. If there is an elegant way to fix it then we should. But I would also be ok if we go out with this version and refine it later.
> 4. For some reason 'Apply for $150M Developer Fund' has come back into the Nav list. This is meant to stay in the banner at the top as in the live docs version.
> 5. I noticed one strange behavior, when using on-page nav (on the right side of the content), we are losing the banner on the page both in the live and test versions.

re.1 and 3: I agree.
re. 2: I agree. Homepage needs updating to add focus on the tools which are missing and take away focus from sOEF (soef is not defunct though and is still what is used by all agent applications. Unless we replace it with a new tool it shouldn't disappear from the documentation but pushed out of focus).
re. 4: this would be fixed when this PR goes in. This branch needs to pull the latest version on `master`.
re. 5: I don't quite understand this. The announcement is always at the top of the screen. When you scroll down or use the links on the right it the page scrolls down and you shouldn't see the banner. Is that what you mean? I also don't know what you mean by live and test versions.

2022-05-18 09:09 UTC, GataKamsky commented
@5A11 

re. 5: Banner disappears when anchoring on the page and is not sticky like the header. It is there when you scroll back up. We can leave this as is.

On rest of the points, I agree with you.

2022-05-18 09:58 UTC, 5A11 commented
l

> @5A11
> 
> re. 5: Banner disappears when anchoring on the page and is not sticky like the header. It is there when you scroll back up. We can leave this as is.
> 
> On rest of the points, I agree with you.

Yes, that is the default behaviour of the announcement bar in material. For example see https://facelessuser.github.io/pymdown-extensions/ 

I'm sure there is a way to make it stick to the top by manually fiddling with the files but might take some time. @StephenBrownFetch can comment on this.

2022-05-20 08:54 UTC, 5A11 requested changes
Can you take out colearn and cosmpy submodule updates from this PR?

2022-05-20 08:55 UTC, 5A11 commented on docs/css/style.css
> -    stroke-dashoffset: -124;
Why delete? I believe these were for the native funding form.

2022-05-20 08:56 UTC, 5A11 commented on docs/index.md
> +    * Learn about to [trade with other agents](../aea/generic-skills-step-by-step). Proceed to the beginner or advanced guides to learn
```suggestion
    * Learn how to [trade with other agents](../aea/generic-skills-step-by-step). Proceed to the beginner or advanced guides to learn
```

2022-05-20 08:57 UTC, 5A11 commented on docs/css/style.css
> +.md-typeset h3, .md-typeset h1, .md-typeset h2 {
Generally good idea to add comment to state what this bit does (similar to `/* overriding colours */` up top).

2022-05-20 08:58 UTC, 5A11 commented on docs/css/style.css
> +.md-typeset h3, .md-typeset h1, .md-typeset h2 {
Similarly below.

2022-05-20 09:05 UTC, StephenBrownFetch commented on docs/css/style.css
> -    stroke-dashoffset: -124;
@5A11 I don't recall deleting these lines, this may have been as a result of merging from main where all the radio and snackbar components were removed

2022-05-20 09:12 UTC, StephenBrownFetch commented on docs/css/style.css
> +.md-typeset h3, .md-typeset h1, .md-typeset h2 {
Sure, line 52 is still overriding headers which had already been mentioned on line 11, but I can add to the below

2022-05-20 09:47 UTC, 5A11 reviewed
I think you forgot to address the shade issue (makes the texts overflow). 
Otherwise looks good.

2022-05-20 10:35 UTC, StephenBrownFetch commented
> I think you forgot to address the link hover shade issue (makes the texts overflow). Otherwise looks good.

Still investigating how to solve this in an elegant way, but if we can push ahead for now while I continue the investigation that would be good. Thanks!

2022-05-20 11:25 UTC, 5A11 commented
> 

If we want to quickly merge this PR, ideally we should remove this feature from this PR and add another PR with the correct hover feature.

I'm happy to merge this in now though only if we address this problem as a priority next (otherwise this could be there for a long time while we are tending to other tasks).

2022-05-20 11:27 UTC, StephenBrownFetch commented
> > 
> 
> If we want to quickly merge this PR, ideally we should remove this feature from this PR and add another PR with the correct hover feature.
> 
> I'm happy to merge this in now though only if we address this problem as a priority next (otherwise this could be there for a long time while we are tending to other tasks).

@5A11 Okay sure. I'll address it in my next PR as a priority

2022-05-22 20:42 UTC, 5A11 approved these changes

2022-05-22 20:42 UTC, merged