Add learn the concepts section: smart contracts
fetchai/docs-archived pull request #267
Opened 2022-07-27 09:39 UTC by FelixNicolaeBucsa

Hey there @5A11 @VijaySharma815 @GataKamsky this PR is for the changes i made following the feedbacks and i have also added the smart contracts section for review. Pls have a view when possible.

2022-07-27 10:42 UTC, VijaySharma815 commented on docs/Native_and_ERC20_FET/how_to_convert_your_fet_tokens.md
> +
Multiple consecutive blank lines [Expected: 1]

2022-07-27 10:49 UTC, FelixNicolaeBucsa commented on docs/Native_and_ERC20_FET/how_to_convert_your_fet_tokens.md
> +
I have removed such blank lines and made some additional changes

2022-07-27 10:52 UTC, VijaySharma815 requested changes

2022-07-27 10:52 UTC, VijaySharma815 commented on docs/Native_and_ERC20_FET/how_to_convert_your_fet_tokens.md
> +
Multiple consecutive blank lines [Expected: 1]

2022-07-27 10:52 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +###Real Estate
No space after hash on atx style heading

2022-07-27 10:52 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +###Supply Chain Management
No space after hash on atx style heading

2022-07-27 10:52 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +Smart contracts and dApps are poised to continue revolutionizing the world of digital agreements. Numerous more businesses will benefit greatly from smart contract technology in the future. Researche
Files should end with a single newline

2022-07-27 10:52 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +
Multiple consecutive blank lines [Expected: 1; Actual: 2]

2022-07-27 10:55 UTC, FelixNicolaeBucsa commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +###Real Estate
I apologize for this, i removed the space unintentionally

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/Native_and_ERC20_FET/how_to_convert_your_fet_tokens.md
> +6.	Press Transfer and allow the Token Bridge to connect with your wallet.
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/Native_and_ERC20_FET/native_and_erc20_fet_before_mainnet_launch.md
> +- BSCscan: <https://bscscan.com/token/0x031b41e504677879370e9dbcf937283a8691fa7f>.
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/Native_and_ERC20_FET/reconciliation_service.md
> +If you have these ready, to begin the reconciliation service visit: <https://browse-fetchhub.fetch.ai/reconciliation> and follow the instructions.
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/learn_the_concepts/agent-based_and_multi-agents_systems.md
> +**Despite their wide applicability, there are still several challenges faced by MAS including coordination between agents, security, and task allocation.**
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/validators.md
> +**Delegated Proof-of-Stake** (i.e. **DPoS**), is a well-liked development of the Proof-of-Stake idea in which network users chose delegates to validate the following block. **Delegates** may also be
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/what_is_a_blockchain.md
> +Varying consensus techniques have different effects on accessibility, security, and sustainability, and not all blockchains are created equally. In fact, the most suitable type of blockchain design n
Files should end with a single newline

2022-07-27 11:28 UTC, VijaySharma815 commented on docs/learn_the_concepts/peer_to_peer_systems.md
> +- [Bisq](https://bisq.network/)
Files should end with a single newline

2022-09-04 07:12 UTC, VijaySharma815 approved these changes

2022-09-04 07:12 UTC, VijaySharma815 commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +Another sector that has started utilizing blockchain technology for safe, trustless, and transparent data sharing is healthcare. The incorporation of smart contracts and full decentralized applicatio
Another sector that has started utilizing blockchain technology for safe, trustless, and transparent data sharing is healthcare -> Another sector that has started utilizing blockchain technology for safe, trustless, and transparent data sharing in healthcare

2022-09-05 08:31 UTC, FelixNicolaeBucsa commented on docs/learn_the_concepts/blockchains/smart_contracts.md
> +Another sector that has started utilizing blockchain technology for safe, trustless, and transparent data sharing is healthcare. The incorporation of smart contracts and full decentralized applicatio
This is not sounding good to me. 

"... data sharing **is** healthcare" sounds more appropriate rather than "... data sharing **in** healthcare" because i do not want to specify a single subject of application but the whole healthcare sector

2022-11-14 13:56 UTC, merged