Feature/responsive
fetchai/docs-archived pull request #68
Opened 2019-12-12 10:34 UTC by bagnall-fetch

2019-12-12 11:13 UTC, devjsc requested changes
Some changes required: 

Debug has been committed
Scroll bar on left hand menu is displayed in desktop mode
When screen is in mobile, text leaves the "Tutorials" link on the main page
Decreasing gap between menu items on desktop would be preferable. 

Please also merge master in before commit too

2019-12-12 13:37 UTC, bagnall-fetch commented
The following work was carried out in this PR:

Rework header component to accept child menu items.
Rework ambassador form to work with mailchimp (rename inputs to match, change radio to checkbox)
Create CheckBox component.
Add href to footer
Modify footer styling to sync with other sites.
Modify header styling to sync with other sites.
Change to hero text.
Fix car animation not to crash on smaller devices.
Fix id/name in TextField and TextArea.
Fix grid layout in TextField and TextArea.
Change video to be IOT video.
Rework styling breakpoints to be mobile first.
Adjust M 't-shirt size' breakpoint.

2019-12-12 14:02 UTC, bagnall-fetch commented
> Some changes required:
> 
> Debug has been committed

debug removed

> Scroll bar on left hand menu is displayed in desktop mode

reworked to remove (not a simple fix unfortunately)

> When screen is in mobile, text leaves the "Tutorials" link on the main page

Which size mobile please?

> Decreasing gap between menu items on desktop would be preferable.

I think we should create a ticket for this as it will involve all websites for consistency. And are we talking no-gap at all?

> 
> Please also merge master in before commit too

2020-01-06 10:38 UTC, devjsc requested changes
Between 960 and 881px the header bar has a larger height than any other menu and needs to be set with a smaller height. 

The Text "Type to search" in the search bar is aligned with content in full screen but loses it's alignment when the menu bar is hidden.

2020-01-08 13:37 UTC, cyenyxe requested changes

2020-01-08 13:37 UTC, cyenyxe commented on .vscode/settings.json
> +{
Please delete and add to `.gitignore`.

2020-01-08 13:37 UTC, cyenyxe commented on docs/index.md
> +    <a id="qs" href="getting-started/quickstart/">
Please restore indentation, as it should be at the same level as the _div_ right above.

2020-01-08 13:37 UTC, cyenyxe commented on docs/sass/media-queries.scss
> +	// If the breakpoint exists in the map.
Could indentation be made consistent across the different file types? Right now (new) CSS files use tabs, whereas the rest use spaces. I think all our projects favor spaces so let's stick to those.

2020-01-08 16:23 UTC, bagnall-fetch commented on docs/index.md
> +    <a id="qs" href="getting-started/quickstart/">
Fixed to 2 space indents as I think that's what is being requested? My preference is generally 4 spaces.

2020-01-08 16:23 UTC, bagnall-fetch commented on docs/sass/media-queries.scss
> +	// If the breakpoint exists in the map.
Indent is using spaces.

2020-01-08 16:24 UTC, bagnall-fetch commented on docs/sass/media-queries.scss
> +	// If the breakpoint exists in the map.
CSS files are generated in the build.

2020-01-09 09:29 UTC, bagnall-fetch commented
Latest commit has reduced header height in the circumstances described by Josh. To do this, needed to change the side menu so that it does not occupy just the remainder of the viewport height and have its own scroll. Instead, I have adopted a technique similar to new.bbc.co.uk that I showed to Josh, whereby the menu replaces the content in the main flow and the whole screen scrolls. This cannot be done for sites with hero sections however, so header height will not match across all sites.

2020-01-09 09:30 UTC, bagnall-fetch commented
I still need to go over the conflicts with Josh.

2020-01-10 09:53 UTC, merged